name: Publish arm-assembly package to GitHub Packages
on:
  release:
    types: [created]
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-java@dd06d9cba3e5552c54d9f8ea23572deb30010f7c # v6.0.0
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Publish arm-assembly package
        run: |
          cd $GITHUB_WORKSPACE/arm-assembly
          # `github.repository_owner` is the build-in context value
          mvn deploy -Dgithub.owner=${{ github.repository_owner }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
